### ISSUE TITLE
[Feature] Support GeyserMC if possible (Edit Watchdog: Minecraft Bedrock Clients connect to Java Server)

### ISSUE THREAD

**Issue by Cameronsplaze** [Cameronsplaze/AWS-ContainerManager#70]
**Is your feature request related to a problem? Please describe.**
Just learned [GeyserMC](https://geysermc.org/) exists, which lets bedrock CLIENTS connect to a java SERVER. It'd be fun to see what it takes to support this, but according to [this issue](https://github.com/doctorray117/minecraft-ondemand/issues/58), you might need BOTH tcp and udp logic for java and bedrock respectively. 

This could mean a re-write of the watchdog logic, so I'd like to wait until https://github.com/Cameronsplaze/AWS-ContainerManager/issues/21 is figured out. It could mean if that works out with just metrics, we solve this issue for free.

I think if possible, I'll just add this to the minecraft-java config with clear comments on what to delete if you don't want it. I thought about maintaining a third config specifically for this, but there'd still be the simple bedrock version anyways. Every config adds considerable time to synth, deploy, and just maintain in general anyways.

**Comment by Cameronsplaze** [comment]
Poked at this a little bit. Was able to connect to the server on a mobile device!

But it only lasted 5 minutes, i.e the watchdog couldn't see the bedrock server connections. Technically I can re-write the watchdog logic to support it watching BOTH tcp and udp at the same time, but there's no point doing that much work unless https://github.com/Cameronsplaze/AWS-ContainerManager/issues/21 doesn't pan out.

**Comment by j1mmie** [comment]
Hi @Cameronsplaze, sorry to ping you, I'm having trouble following the history of this topic and the various possible solutions. I set up a new Minecraft OnDemand server last week and have also been experiencing this issue - my server shuts down 10 minutes after starting up, despite having a Bedrock client connected. Is this expected to be fixed yet?

**Comment by Cameronsplaze** [comment]
Hi @j1mmie, no worries! Especially since this issue is closed, I might not see any reply unless you ping. Keep it up just in case. I didn't think anyone was using the repo yet, so most of the issues are more "personal notes" lol. I'm surprised bedrock would spin it down though, those tend to be LOADS more noisy than java clients. What I'd suggest is:

- Pull from main and re-deploy, I recently fixed something that makes threshold more stable than it used to be.
- Grab the updated value(s) from `./Examples/Minecraft.java.example.yaml` and update your config. Especially the new Watchdog variables.
- Watch the dashboard, and see what the traffic looks like for your specific use-case (More info on [this here](https://github.com/Cameronsplaze/AWS-ContainerManager?tab=readme-ov-file#if-the-container-is-unexpectedly-going-down-or-staying-up)).

Of note though, my next project is moving the [hosted zone](https://github.com/Cameronsplaze/AWS-ContainerManager/issues/81) logic into the leaf stack. I didn't realize there was a restriction on filters, so right now you can only have two leaf stacks per account. I'm not sure if `cdk deploy` is smart enough to update everyone automatically once I do, or if you'll have to destroy/re-deploy everything later. That's the last "breaking change" I currently see for this project, but also why I haven't advertised it yet.
